Flag for disabling cinder agent uuid generation
openstack-exporter/openstack-exporter pull request #193
Opened 2021-05-29 09:52 UTC by alexeymyltsev

This PR add flag for disabling cinder agent uuid generation.

It should fix https://github.com/openstack-exporter/openstack-exporter/issues/190

2021-06-02 19:04 UTC, alexeymyltsev commented
@niedbalski additionally I not sure about this fix https://github.com/openstack-exporter/openstack-exporter/pull/116. As I see in my environment, cinder grouped services by hostname, it mean that hostname should be unique label.

2021-06-04 12:31 UTC, priteau requested changes

2021-06-04 12:31 UTC, priteau commented on README.md
> +                                 Disable UUID generation for Cinder agnets
agnets -> agents

2021-06-04 12:31 UTC, priteau commented on README.md
> +      --disable-service.database
Trailing whitespace added

2021-06-04 12:31 UTC, priteau commented on README.md
> +      --disable-service.orchestration
Trailing whitespace added

2021-06-04 12:31 UTC, priteau commented on main.go
> +	disableCinderAgentUUID   = kingpin.Flag("disable-cinder-agent-uuid", "Disable UUID generation for Cinder agnets").Default("false").Bool()
agnets -> agents

2021-06-10 01:21 UTC, merged